[meta]
# site title, show in <title>
title = "WenHaoxing"

# subtitle, words after title, in description
subtitle = "æ–°ç«™å¼€å¯ğŸ‰ï¼Œæˆ‘è¦åšæŒå†™åšå®¢ï¼ä½†æ˜¯æ‰¾ä¸åˆ°å‰ç½‘ç«™çš„å¤‡ä»½äº†ğŸ˜¢"

# print in html <meta>
keyword = "çš“æ˜Ÿ,ä¸ªäººç½‘ç«™,æŠ€æœ¯,ç”Ÿæ´»,åšå®¢,blog"

# print in html <meta>
desc = "è¿™æ˜¯çš“æ˜Ÿçš„ä¸ªäººæŠ€æœ¯&ç”Ÿæ´»åšå®¢"

# build links for feed, sitemap
domain = "wenhaoxing.cn"

# root path for site# if empty, build as http://{domain}/
root = "http://wenhaoxing.cn/"

# cover page for homepage
cover = "@media/cover.jpg"

# global language,
# its used in global posts and themes, unless pages set lang
lang = "zh"


[[nav]]
link = "/"
title = "Home"
i18n = "home"
# set nav to active status
hover = "index"
blank = false

[[nav]]
link = "/archive"
title = "Archive"
i18n = "archive"
hover = "archive"

[[nav]]
link = "/about"
title = "About"
i18n = "about"
hover = "about"

[[nav]]
link = "https://github.com/wenstar"
title = "Source"
i18n = "source"
# browser open in new tab
blank = true

[[author]]
name = "çš“æ˜Ÿ"
email = "wenhaoxing@mail.nankai.edu.cn"
url = "http://wenhaoxing.cn"
avatar = "@media/author.png"
bio = "The owner and writer of this blog."

# comment settings
# please only set one value
# if multi values, it prints all comment iframes
[comment]
# disqus site name
disqus = ""
# duoshuo short name
duoshuo = ""

# analytics settings
# please only set one value
# if multi values, it prints all analytics codes
[analytics]
# google analytics, need as UA-XXXXX-Y
google = ""
# baidu analytics, need hash-code in hm.js?hash-code
baidu = ""

[build]
# disable_post disable to read & compile post data
disable_post = false
# disable_page disable to read & compile page data
disable_page = false
# post_dir set posts directory
post_dir = "post"
# page_dir set pages directory
page_dir = "page"
# media dir set media directory, based on source directory
media_dir = "media"
